language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"

notifications:
  irc: "irc.freenode.org##atoum"

sudo: false

cache:
  directories:
    - vendor

script:
  - composer update $COMPOSER_PREFER
  - ./vendor/bin/atoum --test-ext -p 'php -n -ddate.timezone=UTC'
